apiVersion: v1
kind: ServiceAccount
metadata:
  name: nifi-leader-election
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nifi-leader-election
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nifi-leader-election
subjects:
- kind: ServiceAccount
  name: nifi-leader-election
roleRef:
  kind: Role
  name: nifi-leader-election
  apiGroup: rbac.authorization.k8s.io