---
apiVersion: v1
kind: Service
metadata:
  name: nifi-0
  labels:
    app: nifi
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: nifi-0
  ports:
    - name: https
      port: 8443
      targetPort: 8443